### ISSUE TITLE
Update README once all API methods are supported

### ISSUE THREAD

**Issue by juhalehtonen** [juhalehtonen/ex_uptimerobot#4]
The README currently mentions how not all features of the Uptime Robot API are supported. This should be corrected once all API method wrappers are added.

**Comment by sbulage** [comment]
@juhalehtonen you want to add information from this URL(https://hexdocs.pm/ex_uptimerobot/api-reference.html) to README.md file ...?

**Comment by juhalehtonen** [comment]
Hey. No, sorry for the confusion. This issue refers to the fact that the current README states "not all functionality offered by the Uptime Robot API is yet present.". Once all API methods are covered, the README should then be updated.
