### ISSUE TITLE
Replace test API calls with mocks

### ISSUE THREAD

**Issue by juhalehtonen** [juhalehtonen/ex_uptimerobot#6]
Currently the tests are calling the real API, which can result in unexpected behaviour and inconsistent results (timeouts at any point in time can make the build fail).

This could be achieved with something like https://github.com/jjh42/mock

**Comment by ppsmirnov** [comment]
Can I take this one?

**Comment by juhalehtonen** [comment]
Hey, absolutely! Did you plan on using the mock library I linked in the description, or do you have ideas for something else?

**Comment by ppsmirnov** [comment]
I think, I'll go with the one you linked.
